import { FileSystemManager } from "@/shared/managers/FileSystemManager";
import {
  VIEW_MODE,
  ZOOM_DEFAULT,
  DEFAULT_DATE_FORMAT,
  DEFAULT_SIDEBAR_OPACITY,
  DEFAULT_STARTUP_MODE,
} from "@/shared/constants";

import type { State } from "./types";

// Default context value; also the seed used before the App provider mounts.
export const initialState: State = {
  fs: new FileSystemManager(),
  volumes: [],
  setVolumes: () => {},
  tabs: [],
  activeTabId: "",
  newTab: () => {},
  closeTab: () => {},
  selectTab: () => {},
  path: "",
  setPath: () => {},
  canGoBack: false,
  canGoForward: false,
  goBack: () => {},
  goForward: () => {},
  dirContent: [],
  setDirContent: () => {},
  accessDenied: false,
  view: VIEW_MODE.GRID,
  setView: () => {},
  showHidden: false,
  toggleShowHidden: () => {},
  hideSystemRecents: true,
  toggleHideSystemRecents: () => {},
  showToasts: true,
  toggleShowToasts: () => {},
  zoom: ZOOM_DEFAULT,
  zoomIn: () => {},
  zoomOut: () => {},
  setZoomTo: () => {},
  defaultZoom: ZOOM_DEFAULT,
  setDefaultZoom: () => {},
  dateFormat: DEFAULT_DATE_FORMAT,
  setDateFormat: () => {},
  sidebarOpacity: DEFAULT_SIDEBAR_OPACITY,
  setSidebarOpacity: () => {},
  startupMode: DEFAULT_STARTUP_MODE,
  setStartupMode: () => {},
  homePath: "",
  setHomePath: () => {},
  savingSettings: false,
  search: "",
  setSearch: () => {},
  refreshDir: () => {},
  infoPanelOpen: false,
  toggleInfoPanel: () => {},
};
